export { default as Header } from "./Header"
export { default as EditStudentProfile } from "./EditStudentProfile"
export { default as QuestionsList } from "./QuestionsList"
export { default as AddNewQuestion } from "./AddNewQuestion"
export { default as AddNewStudent } from "./AddNewStudent"
export { default as NewQuestionCard } from "./NewQuestionCard"
export { default as AddNewStaff } from "./AddNewStaff"
export { default as Footer } from "./Footer"
